spring:
  liquibase:
        change-log: classpath:db/changelog/db.changelog-master.yaml
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: aszx12qw
    url: jdbc:postgresql://localhost:5432/library

#  banner:
#    charset: UTF-8
#    image:
##      location: banner/Bug.jpg
#      width: 50
#      height: 50
#      margin: 25