spring:
  messages:
    basename: bundle/messages

  data:
    mongodb:
      database: library
  mvc:
    locale-resolver: accept_header #just don't forget)
    locale: ru_RU
    message-codes-resolver-format: postfix_error_code
