spring:
  messages:
    basename: bundle/messages

  data:
    mongodb:
      port: 27017
      host: localhost
      database: library
  mvc:
    locale-resolver: accept_header #just don't forget)
    locale: ru_RU
    message-codes-resolver-format: postfix_error_code
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
  file: logging.log
server:
  port: 8083
request:
  max: 100

management:
  endpoint:
    health:
      show-details: when_authorized
  endpoints:
    web:
      exposure:
        include:
          - health
          - loggers
          - logfile
          - env
          - beans
          - metrics
          - configprops
          - shutdown
