spring:
  liquibase:
        change-log: classpath:db/changelog/db.changelog-master.yaml
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${postgres_login}
    password: ${postgres_pass}
    url: jdbc:postgresql://localhost:5432/library